// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuP7kmE1TwDhkiu9-K699x9wSmqVMKVPY',
    appId: '1:908744240965:web:64abfd546a3127d7f7d82c',
    messagingSenderId: '908744240965',
    projectId: 'treefficiency-f3610',
    authDomain: 'treefficiency-f3610.firebaseapp.com',
    storageBucket: 'treefficiency-f3610.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KIYp8zCfS89B7Cs7uPJiXxlkmVGs1Vo',
    appId: '1:908744240965:android:1c65eff99dcd234af7d82c',
    messagingSenderId: '908744240965',
    projectId: 'treefficiency-f3610',
    storageBucket: 'treefficiency-f3610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3fKdi29roHtdLr0neHL8VswVmKaKs7bo',
    appId: '1:908744240965:ios:04be19e3e2ad36edf7d82c',
    messagingSenderId: '908744240965',
    projectId: 'treefficiency-f3610',
    storageBucket: 'treefficiency-f3610.appspot.com',
    iosBundleId: 'com.example.treefficiency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3fKdi29roHtdLr0neHL8VswVmKaKs7bo',
    appId: '1:908744240965:ios:de6628a58377c078f7d82c',
    messagingSenderId: '908744240965',
    projectId: 'treefficiency-f3610',
    storageBucket: 'treefficiency-f3610.appspot.com',
    iosBundleId: 'com.example.treefficiency.RunnerTests',
  );
}
